//
//  PostsListInteractor.swift
//  Viper-RxSwift-Example
//
//  Created by Nikita Velichkin on 19/01/2020.
//  Copyright (c) 2020 Nikita Velichkin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Moya
import RxSwift

final class PostsListInteractor {
    var provider: MoyaProvider<PostsManagerPath>
    
    init(provider : MoyaProvider<PostsManagerPath> = .init() ) {
        self.provider = provider
    }
}

// MARK: - Extensions -

extension PostsListInteractor: PostsListInteractorInterface {
    func fetch() -> Observable<[Post]> {
        return provider.rx
            .request(.getPosts)
            .map([Post].self)
            .asObservable()
    }
}
