//
//  PostsListInterfaces.swift
//  Viper-RxSwift-Example
//
//  Created by Nikita Velichkin on 19/01/2020.
//  Copyright (c) 2020 Nikita Velichkin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa
import RxDataSources

enum PostsList {

    struct ViewOutput {
        var didSelectPost: ControlEvent<Post>
    }

    struct ViewInput {
        var posts: Driver<[AnimatableSectionModel<String, Post>]>
    }

}

protocol PostsListWireframeInterface: WireframeInterface {
    func didSelectPost(_ post: Post)
}

protocol PostsListViewInterface: ViewInterface {
    var disposeBag: DisposeBag { get }
}

protocol PostsListPresenterInterface: PresenterInterface {
    func configure(with output: PostsList.ViewOutput) -> PostsList.ViewInput
}

protocol PostsListInteractorInterface: InteractorInterface {
    func fetch() -> Observable<[Post]>
}
