//
//  PostsListWireframe.swift
//  Viper-RxSwift-Example
//
//  Created by Nikita Velichkin on 19/01/2020.
//  Copyright (c) 2020 Nikita Velichkin. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class PostsListWireframe: BaseWireframe {

    // MARK: - Module setup -

    init() {
        let moduleViewController = PostsListViewController()
        super.init(viewController: moduleViewController)

        let interactor = PostsListInteractor()
        let presenter = PostsListPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PostsListWireframe: PostsListWireframeInterface {
    func didSelectPost(_ post: Post) {
        viewController.present(UIViewController(), animated: true, completion: nil)
    }
    
}
